version: "3"

services:
  k6-load-test:
    container_name: k6-load-test
    image: grafana/k6:0.38.3
    volumes:
      - ./tests:/src
    # we run different file in container because we cannot generate custom html report
    command: run /src/in-docker.js
